automatic tests running on push

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -14,9 +14,6 @@ env:
 
 jobs:
   build:
-    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
-    # You can convert this to a matrix build if you need cross-platform coverage.
-    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
@@ -30,6 +27,16 @@ jobs:
     - name: Build
       run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
 
-    - name: Test
+    - name: Run CTest
       working-directory: ${{github.workspace}}/build
       run: ctest -C ${{env.BUILD_TYPE}}
+
+    - name: Run Google Tests
+      run: |
+        if [ -f ${{github.workspace}}/src/test/VDSProject_test ]; then
+          chmod +x ${{github.workspace}}/src/test/VDSProject_test
+          ${{github.workspace}}/src/test/VDSProject_test
+        else
+          echo "Test binary not found!"
+          exit 1
+        fi
